---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-minutely-cron-job
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: example-minutely-cron-job
          containers:
          - name: batch-container
            image: amazon/aws-cli
            command: ["aws", "sts", "get-caller-identity"]
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi
          restartPolicy: Never

