apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-daily-cron-job
spec:
  schedule: "15 00 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  suspend: False
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: batch-container
            image: python:3.8-slim
            command: ["python", "-c", "print('hello')"]
          restartPolicy: Never
