---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-minutely-cron-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: sample-minutely-cron-job
          containers:
          - name: batch-container
            image: python:3.8-slim
            command: ["python", "-c", "print('hello')"]
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-minutely-cron-job
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-minutely-cron-job-role
  namespace: default
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-minutely-cron-job-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sample-minutely-cron-job-role
subjects:
- kind: ServiceAccount
  name: sample-minutely-cron-job
  namespace: default

