---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-hourly-cron-job
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  suspend: False
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: sample-hourly-cron-job-role
          containers:
          - name: batch-container
            image: python:3.8-slim
            command: ["python", "-c", "print('hello')"]
          restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-hourly-cron-job-role
  namespace: default
